/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  awX
 *  axb
 *  fAD
 *  fAW
 *  fAa
 *  fBt
 *  fBv
 *  fBz
 *  fDe
 *  fDu
 *  fEA
 *  fEy
 *  fHi
 *  fHk
 *  fHs
 *  fHu
 *  fHv
 *  fJD
 *  fJe
 *  fJn
 *  fJt
 *  fJw
 *  fJx
 *  fKK
 *  fKM
 *  fMz
 *  fRO
 *  fRP
 *  fRV
 *  fRt
 *  fRu
 *  fRz
 *  fSM
 *  fSd
 *  fSj
 *  fyY
 *  fyw
 *  fzT
 *  fzU
 *  fzW
 *  fza
 *  fze
 *  fzq
 *  fzv
 *  fzx
 */
import java.awt.Insets;
import java.util.Stack;

public class cII
implements fHk {
    private Stack<fHs> nei = new Stack();
    private fHu nej;

    public fHi a(fHu fHu2, fHs fHs2) {
        this.nej = fHu2;
        this.nei.push(fHs2);
        fHs fHs3 = this.nei.peek();
        fEy fEy2 = new fEy();
        fEy2.aVI();
        fEy2.setElementMap(fHs3);
        fEy2.setPrefSize(new fSM(800, 300));
        fEy2.guy();
        fRP fRP2 = new fRP();
        fRP2.aVI();
        fRP2.setElementMap(fHs3);
        fRP2.setAlign(fzW.tLg);
        fRP2.setInitValue(true);
        fEy2.X((fHi)fRP2);
        fRP2.guy();
        fRP2.onChildrenAdded();
        fAW fAW2 = fAW.checkOut();
        fAW2.setElementMap(fHs3);
        fAW2.setExpandable(false);
        fAW2.setNonBlocking(false);
        fAW2.setPrefSize(new fSM(18, 100));
        fAW2.setStyle("itemInventoryBarBackground");
        fEy2.X((fHi)fAW2);
        fAW2.guy();
        fRt fRt2 = new fRt();
        fRt2.aVI();
        fAW2.X((fHi)fRt2);
        fRt2.guy();
        fRt2.onChildrenAdded();
        fEA fEA2 = new fEA();
        fEA2.aVI();
        fEA2.setElementMap(fHs3);
        fAW2.X((fHi)fEA2);
        fEA2.guy();
        fRu fRu2 = fRu.checkOut();
        fRu2.setElementMap(fHs3);
        fRu2.setData(fzT.tKw);
        fEA2.X((fHi)fRu2);
        fRu2.guy();
        fRu2.onChildrenAdded();
        fRt fRt3 = new fRt();
        fRt3.aVI();
        fEA2.X((fHi)fRt3);
        fRt3.guy();
        fRt3.onChildrenAdded();
        fBv fBv2 = new fBv();
        fBv2.aVI();
        fBv2.setElementMap(fHs3);
        fBv2.setNonBlocking(true);
        fBv2.setOrientation(fzU.tKC);
        fBv2.setStyle("bold");
        fBv2.setText("Editeur de personnage");
        fEA2.X((fHi)fBv2);
        fBv2.guy();
        fRu fRu3 = fRu.checkOut();
        fRu3.setElementMap(fHs3);
        fRu3.setData(fzT.tKw);
        fBv2.X((fHi)fRu3);
        fRu3.guy();
        fRu3.onChildrenAdded();
        fBv fBv3 = fBv2;
        fzq fzq2 = (fzq)fBv3.getAppearance();
        fzq2.setElementMap(fHs3);
        fBv2.X((fHi)fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fHs3);
        fzv2.setInsets(new Insets(0, 0, 20, 0));
        fzq2.X((fHi)fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fBv2.onChildrenAdded();
        fAD fAD2 = new fAD();
        fAD2.aVI();
        fAD2.setElementMap(fHs3);
        fMz fMz2 = new fMz();
        fMz2.vw("unloadDialog");
        fAD2.setOnClick(fMz2);
        fAD2.setStyle("smallDelete");
        fEA2.X((fHi)fAD2);
        fAD2.guy();
        fRu fRu4 = fRu.checkOut();
        fRu4.setElementMap(fHs3);
        fRu4.setData(fzT.tKx);
        fAD2.X((fHi)fRu4);
        fRu4.guy();
        fRu4.onChildrenAdded();
        fAD fAD3 = fAD2;
        fyM fyM2 = (fyM)((Object)fAD3.getAppearance());
        fyM2.setElementMap(fHs3);
        fAD2.X((fHi)fyM2);
        fyM2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fHs3);
        fzv3.setInsets(new Insets(10, 0, 0, 0));
        fyM2.X((fHi)fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyM2.onChildrenAdded();
        fAD2.onChildrenAdded();
        fEA2.onChildrenAdded();
        fAW2.onChildrenAdded();
        fAW fAW3 = fAW.checkOut();
        fAW3.setElementMap(fHs3);
        fAW3.setNonBlocking(false);
        fAW3.setStyle("brownInventoryBackground");
        fEy2.X((fHi)fAW3);
        fAW3.guy();
        fRz fRz2 = fRz.checkOut();
        fRz2.setHorizontal(false);
        fAW3.X((fHi)fRz2);
        fRz2.guy();
        fRz2.onChildrenAdded();
        fAW fAW4 = fAW3;
        fyS fyS2 = fAW4.getAppearance();
        fyS2.setElementMap(fHs3);
        fAW3.X((fHi)fyS2);
        fyS2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fHs3);
        fzx2.setInsets(new Insets(15, 5, 10, 7));
        fyS2.X((fHi)fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fyS2.onChildrenAdded();
        fAW fAW5 = fAW.checkOut();
        fAW5.setElementMap(fHs3);
        fAW3.X((fHi)fAW5);
        fAW5.guy();
        fRz fRz3 = fRz.checkOut();
        fRz3.setAlign(fAa.tLL);
        fRz3.setHorizontal(false);
        fAW5.X((fHi)fRz3);
        fRz3.guy();
        fRz3.onChildrenAdded();
        fAW fAW6 = fAW.checkOut();
        fAW6.setElementMap(fHs3);
        fAW6.setExpandable(false);
        fAW5.X((fHi)fAW6);
        fAW6.guy();
        fRz fRz4 = fRz.checkOut();
        fRz4.setAlign(fAa.tLN);
        fAW6.X((fHi)fRz4);
        fRz4.guy();
        fRz4.onChildrenAdded();
        fBv fBv4 = new fBv();
        fBv4.aVI();
        fBv4.setElementMap(fHs3);
        fBv4.setExpandable(false);
        fBv4.setStyle("whiteTitle");
        String string = "Niveau du personnage%colon%";
        string = string.replace("%colon%", fyw.gqw().k("colon", new Object[0]));
        fBv4.setText(string);
        fAW6.X((fHi)fBv4);
        fBv4.guy();
        fBv4.onChildrenAdded();
        String string2 = "level";
        fDu fDu2 = new fDu();
        fDu2.aVI();
        fDu2.setElementMap(fHs3);
        if (fHs3 != null && string2 != null) {
            fHs3.a(string2, (fHv)fDu2);
        }
        fDu2.setExpandable(false);
        fDu2.setPrefSize(new fSM(150, 0));
        fDu2.setRestrict("[0-9]+");
        fDu2.setStyle("dark");
        fAW6.X((fHi)fDu2);
        fDu2.guy();
        fSj fSj2 = fSj.checkOut();
        fSj2.setElementMap(fHs3);
        fSj2.setAttribute("text");
        fSj2.setField("level");
        fSj2.setName("localPlayer");
        fDu2.X((fHi)fSj2);
        fSj2.guy();
        fSj2.onChildrenAdded();
        fDu2.onChildrenAdded();
        fAD fAD4 = new fAD();
        fAD4.aVI();
        fAD4.setElementMap(fHs3);
        fAD4.setExpandable(false);
        fMz fMz3 = new fMz();
        fMz3.vw("wakfu.adminCharacterEditor:validLevel");
        fAD4.setOnClick(fMz3);
        fAD4.setStyle("smallValid");
        fAW6.X((fHi)fAD4);
        fAD4.guy();
        fAD4.onChildrenAdded();
        fDe fDe2 = new fDe();
        fDe2.aVI();
        fDe2.setElementMap(fHs3);
        fAW6.X((fHi)fDe2);
        fDe2.guy();
        fDe2.onChildrenAdded();
        fAD fAD5 = new fAD();
        fAD5.aVI();
        fAD5.setElementMap(fHs3);
        fAD5.setExpandable(false);
        fMz fMz4 = new fMz();
        fMz4.vw("wakfu.adminCharacterEditor:openCharacterColorEditor");
        fAD5.setOnClick(fMz4);
        fAD5.setText("\u00c9diter les couleurs");
        fAW6.X((fHi)fAD5);
        fAD5.guy();
        fAD fAD6 = fAD5;
        fyM fyM3 = (fyM)((Object)fAD6.getAppearance());
        fyM3.setElementMap(fHs3);
        fAD5.X((fHi)fyM3);
        fyM3.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fHs3);
        fzx3.setInsets(new Insets(2, 10, 2, 10));
        fyM3.X((fHi)fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fHs3);
        fzv4.setInsets(new Insets(0, 0, 0, 10));
        fyM3.X((fHi)fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyM3.onChildrenAdded();
        fAD5.onChildrenAdded();
        fAW6.onChildrenAdded();
        fAW fAW7 = fAW.checkOut();
        fAW7.setElementMap(fHs3);
        fAW7.setExpandable(false);
        fAW7.setPrefSize(new fSM(0, 7));
        fAW7.setStyle("lineSeparator");
        fAW5.X((fHi)fAW7);
        fAW7.guy();
        fAW fAW8 = fAW7;
        fyS fyS3 = fAW8.getAppearance();
        fyS3.setElementMap(fHs3);
        fAW7.X((fHi)fyS3);
        fyS3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fHs3);
        fzv5.setInsets(new Insets(5, 0, 2, 0));
        fyS3.X((fHi)fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fyS3.onChildrenAdded();
        fAW7.onChildrenAdded();
        fBv fBv5 = new fBv();
        fBv5.aVI();
        fBv5.setElementMap(fHs3);
        fBv5.setExpandable(false);
        fBv5.setStyle("whiteTitle");
        fBv5.setText("Sorts (setLevel) :");
        fAW5.X((fHi)fBv5);
        fBv5.guy();
        fBv5.onChildrenAdded();
        fBz fBz2 = new fBz();
        fBz2.aVI();
        fBz2.setElementMap(fHs3);
        fBz2.setCellSize(new fSM(350, 25));
        fBz2.setExpandable(false);
        fBz2.setHorizontal(false);
        fBz2.setPrefSize(new fSM(350, 150));
        fAW5.X((fHi)fBz2);
        fBz2.guy();
        fSj fSj3 = fSj.checkOut();
        fSj3.setElementMap(fHs3);
        fSj3.setAttribute("content");
        fSj3.setName("spellsList");
        fBz2.X((fHi)fSj3);
        fSj3.guy();
        fSj3.onChildrenAdded();
        fJe fJe2 = new fJe();
        fJe2.aVI();
        fJe2.setElementMap(fHs3);
        fBz2.X((fHi)fJe2);
        fJe2.guy();
        fJt fJt2 = new fJt();
        fJt2.aVI();
        fJt2.setElementMap(fHs3);
        fJe2.X((fHi)fJt2);
        fJt2.guy();
        fJx fJx2 = new fJx();
        fJx2.aVI();
        fJx2.setElementMap(fHs3);
        fJt2.X((fHi)fJx2);
        fJx2.guy();
        fJD fJD2 = new fJD();
        fJD2.aVI();
        fJD2.setElementMap(fHs3);
        fJx2.X((fHi)fJD2);
        fJD2.guy();
        fJD2.onChildrenAdded();
        fJx2.onChildrenAdded();
        fJt2.onChildrenAdded();
        String string3 = "spell";
        fRV fRV2 = new fRV();
        fRV2.aVI();
        fRV2.setElementMap(fHs3);
        if (fHs3 != null && string3 != null) {
            fHs3.a(string3, (fHv)fRV2);
        }
        fJe2.X((fHi)fRV2);
        fRV2.guy();
        fSd fSd2 = new fSd();
        fSd2.aVI();
        fSd2.setElementMap(fHs3);
        fSd2.setAttribute("value");
        fRV2.X((fHi)fSd2);
        fSd2.guy();
        fSd2.onChildrenAdded();
        fRV2.onChildrenAdded();
        fAW fAW9 = fAW.checkOut();
        fAW9.setElementMap(fHs3);
        fJe2.X((fHi)fAW9);
        fAW9.guy();
        fRz fRz5 = fRz.checkOut();
        fRz5.setAlign(fAa.tLN);
        fAW9.X((fHi)fRz5);
        fRz5.guy();
        fRz5.onChildrenAdded();
        fBt fBt2 = new fBt();
        fBt2.aVI();
        fBt2.setElementMap(fHs3);
        fBt2.setDisplaySize(new fSM(26, 26));
        fBt2.setExpandable(false);
        fBt2.setNonBlocking(true);
        fBt2.setPrefSize(new fSM(39, 0));
        fBt2.setScaled(false);
        fAW9.X((fHi)fBt2);
        fBt2.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fHs3);
        fBt2.X((fHi)fze2);
        fze2.guy();
        fSd fSd3 = new fSd();
        fSd3.aVI();
        fSd3.setElementMap(fHs3);
        fSd3.setAttribute("texture");
        fSd3.setField("smallIconUrl");
        fze2.X((fHi)fSd3);
        fSd3.guy();
        fSd3.onChildrenAdded();
        fze2.onChildrenAdded();
        fBt2.onChildrenAdded();
        fBv fBv6 = new fBv();
        fBv6.aVI();
        fBv6.setElementMap(fHs3);
        fBv6.setExpandable(false);
        fBv6.setPrefSize(new fSM(200, 0));
        fBv6.setStyle("whiteBold");
        fAW9.X((fHi)fBv6);
        fBv6.guy();
        fSd fSd4 = new fSd();
        fSd4.aVI();
        fSd4.setElementMap(fHs3);
        fSd4.setAttribute("text");
        fSd4.setField("name");
        fBv6.X((fHi)fSd4);
        fSd4.guy();
        fSd4.onChildrenAdded();
        fBv6.onChildrenAdded();
        String string4 = "spellLevelEditor";
        fDu fDu3 = new fDu();
        fDu3.aVI();
        fDu3.setElementMap(fHs3);
        if (fHs3 != null && string4 != null) {
            fHs3.a(string4, (fHv)fDu3);
        }
        fDu3.setExpandable(false);
        fDu3.setPrefSize(new fSM(50, 0));
        fDu3.setRestrict("[0-9]+");
        fDu3.setStyle("dark");
        fAW9.X((fHi)fDu3);
        fDu3.guy();
        fSd fSd5 = new fSd();
        fSd5.aVI();
        fSd5.setElementMap(fHs3);
        fSd5.setAttribute("text");
        fSd5.setField("level");
        fDu3.X((fHi)fSd5);
        fSd5.guy();
        fSd5.onChildrenAdded();
        fDu3.onChildrenAdded();
        fAD fAD7 = new fAD();
        fAD7.aVI();
        fAD7.setElementMap(fHs3);
        fAD7.setExpandable(false);
        fMz fMz5 = new fMz();
        fMz5.vw("wakfu.adminCharacterEditor:validSpellLevel(spell,spellLevelEditor)");
        fAD7.setOnClick(fMz5);
        fAD7.setStyle("smallValid");
        fAW9.X((fHi)fAD7);
        fAD7.guy();
        fAD7.onChildrenAdded();
        fAW9.onChildrenAdded();
        fJe2.onChildrenAdded();
        fBz2.onChildrenAdded();
        fAW fAW10 = fAW.checkOut();
        fAW10.setElementMap(fHs3);
        fAW10.setExpandable(false);
        fAW10.setPrefSize(new fSM(0, 7));
        fAW10.setStyle("lineSeparator");
        fAW5.X((fHi)fAW10);
        fAW10.guy();
        fAW fAW11 = fAW10;
        fyS fyS4 = fAW11.getAppearance();
        fyS4.setElementMap(fHs3);
        fAW10.X((fHi)fyS4);
        fyS4.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fHs3);
        fzv6.setInsets(new Insets(5, 0, 2, 0));
        fyS4.X((fHi)fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fyS4.onChildrenAdded();
        fAW10.onChildrenAdded();
        fBv fBv7 = new fBv();
        fBv7.aVI();
        fBv7.setElementMap(fHs3);
        fBv7.setExpandable(false);
        fBv7.setStyle("whiteTitle");
        fBv7.setText("Skills \u00e0 apprendre :");
        fAW5.X((fHi)fBv7);
        fBv7.guy();
        fBv7.onChildrenAdded();
        fBz fBz3 = new fBz();
        fBz3.aVI();
        fBz3.setElementMap(fHs3);
        fBz3.setCellSize(new fSM(350, 25));
        fBz3.setExpandable(false);
        fBz3.setHorizontal(false);
        fBz3.setPrefSize(new fSM(350, 100));
        fAW5.X((fHi)fBz3);
        fBz3.guy();
        fBz fBz4 = fBz3;
        fza fza2 = (fza)fBz4.getAppearance();
        fza2.setElementMap(fHs3);
        fBz3.X((fHi)fza2);
        fza2.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fHs3);
        fzv7.setInsets(new Insets(0, 0, 10, 0));
        fza2.X((fHi)fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fza2.onChildrenAdded();
        fSj fSj4 = fSj.checkOut();
        fSj4.setElementMap(fHs3);
        fSj4.setAttribute("content");
        fSj4.setName("craftSkillsList");
        fBz3.X((fHi)fSj4);
        fSj4.guy();
        fSj4.onChildrenAdded();
        fJe fJe3 = new fJe();
        fJe3.aVI();
        fJe3.setElementMap(fHs3);
        fBz3.X((fHi)fJe3);
        fJe3.guy();
        fJt fJt3 = new fJt();
        fJt3.aVI();
        fJt3.setElementMap(fHs3);
        fJe3.X((fHi)fJt3);
        fJt3.guy();
        fJx fJx3 = new fJx();
        fJx3.aVI();
        fJx3.setElementMap(fHs3);
        fJt3.X((fHi)fJx3);
        fJx3.guy();
        fJD fJD3 = new fJD();
        fJD3.aVI();
        fJD3.setElementMap(fHs3);
        fJx3.X((fHi)fJD3);
        fJD3.guy();
        fJD3.onChildrenAdded();
        fJx3.onChildrenAdded();
        fJt3.onChildrenAdded();
        String string5 = "skill";
        fRV fRV3 = new fRV();
        fRV3.aVI();
        fRV3.setElementMap(fHs3);
        if (fHs3 != null && string5 != null) {
            fHs3.a(string5, (fHv)fRV3);
        }
        fJe3.X((fHi)fRV3);
        fRV3.guy();
        fSd fSd6 = new fSd();
        fSd6.aVI();
        fSd6.setElementMap(fHs3);
        fSd6.setAttribute("value");
        fRV3.X((fHi)fSd6);
        fSd6.guy();
        fSd6.onChildrenAdded();
        fRV3.onChildrenAdded();
        fAW fAW12 = fAW.checkOut();
        fAW12.setElementMap(fHs3);
        fJe3.X((fHi)fAW12);
        fAW12.guy();
        fRO fRO2 = new fRO();
        fRO2.aVI();
        fRO2.setAdaptToContentSize(true);
        fAW12.X((fHi)fRO2);
        fRO2.guy();
        fRO2.onChildrenAdded();
        this.R(fAW12);
        this.c(fAW12);
        fAW12.onChildrenAdded();
        fJe3.onChildrenAdded();
        fBz3.onChildrenAdded();
        this.d(fAW5);
        this.e(fAW5);
        fAW5.onChildrenAdded();
        fAW3.onChildrenAdded();
        fEy2.onChildrenAdded();
        return fEy2;
    }

    public fHi R(fAW fAW2) {
        fHs fHs2 = this.nei.peek();
        fAD fAD2 = new fAD();
        fAD2.aVI();
        fAD2.setElementMap(fHs2);
        fAD2.setExpandable(false);
        fMz fMz2 = new fMz();
        fMz2.vw("wakfu.adminCharacterEditor:learnSkill(skill)");
        fAD2.setOnClick(fMz2);
        fAW2.X((fHi)fAD2);
        fAD2.guy();
        fRP fRP2 = new fRP();
        fRP2.aVI();
        fRP2.setElementMap(fHs2);
        fRP2.setAlign(fzW.tLg);
        fRP2.setSize(new fSM(100.0f, 100.0f));
        fAD2.X((fHi)fRP2);
        fRP2.guy();
        fRP2.onChildrenAdded();
        fAD2.onChildrenAdded();
        return fAD2;
    }

    public fHi c(fAW fAW2) {
        fHs fHs2 = this.nei.peek();
        fAW fAW3 = fAW.checkOut();
        fAW3.setElementMap(fHs2);
        fAW2.X((fHi)fAW3);
        fAW3.guy();
        fRP fRP2 = new fRP();
        fRP2.aVI();
        fRP2.setElementMap(fHs2);
        fRP2.setAlign(fzW.tLg);
        fRP2.setSize(new fSM(100.0f, 100.0f));
        fAW3.X((fHi)fRP2);
        fRP2.guy();
        fRP2.onChildrenAdded();
        fAW fAW4 = fAW3;
        fyS fyS2 = fAW4.getAppearance();
        fyS2.setElementMap(fHs2);
        fAW3.X((fHi)fyS2);
        fyS2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fHs2);
        fzx2.setInsets(new Insets(5, 5, 5, 5));
        fyS2.X((fHi)fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fyS2.onChildrenAdded();
        fRz fRz2 = fRz.checkOut();
        fRz2.setAlign(fAa.tLN);
        fAW3.X((fHi)fRz2);
        fRz2.guy();
        fRz2.onChildrenAdded();
        fBt fBt2 = new fBt();
        fBt2.aVI();
        fBt2.setElementMap(fHs2);
        fBt2.setDisplaySize(new fSM(26, 26));
        fBt2.setExpandable(false);
        fBt2.setNonBlocking(true);
        fBt2.setPrefSize(new fSM(30, 0));
        fBt2.setScaled(false);
        fAW3.X((fHi)fBt2);
        fBt2.guy();
        fSd fSd2 = new fSd();
        fSd2.aVI();
        fSd2.setElementMap(fHs2);
        fSd2.setAttribute("style");
        fSd2.setField("craftIcon");
        fBt2.X((fHi)fSd2);
        fSd2.guy();
        fSd2.onChildrenAdded();
        fBt2.onChildrenAdded();
        fBv fBv2 = new fBv();
        fBv2.aVI();
        fBv2.setElementMap(fHs2);
        fBv2.setExpandable(false);
        fBv2.setNonBlocking(true);
        fBv2.setPrefSize(new fSM(200, 0));
        fBv2.setStyle("bold");
        fAW3.X((fHi)fBv2);
        fBv2.guy();
        fSd fSd3 = new fSd();
        fSd3.aVI();
        fSd3.setElementMap(fHs2);
        fSd3.setAttribute("text");
        fSd3.setField("name");
        fBv2.X((fHi)fSd3);
        fSd3.guy();
        fSd3.onChildrenAdded();
        fBv2.onChildrenAdded();
        fAW3.onChildrenAdded();
        return fAW3;
    }

    public fHi d(fAW fAW2) {
        fHs fHs2 = this.nei.peek();
        fBv fBv2 = new fBv();
        fBv2.aVI();
        fBv2.setElementMap(fHs2);
        fBv2.setExpandable(false);
        fBv2.setStyle("whiteTitle");
        fBv2.setText("Skills (addXp) :");
        fAW2.X((fHi)fBv2);
        fBv2.guy();
        fBv2.onChildrenAdded();
        return fBv2;
    }

    public fHi e(fAW fAW2) {
        fHs fHs2 = this.nei.peek();
        fBz fBz2 = new fBz();
        fBz2.aVI();
        fBz2.setElementMap(fHs2);
        fBz2.setCellSize(new fSM(360, 25));
        fBz2.setExpandable(false);
        fBz2.setHorizontal(false);
        fBz2.setPrefSize(new fSM(360, 100));
        fAW2.X((fHi)fBz2);
        fBz2.guy();
        fSj fSj2 = fSj.checkOut();
        fSj2.setElementMap(fHs2);
        fSj2.setAttribute("content");
        fSj2.setField("craft/allKnownCrafts");
        fSj2.setName("localPlayer");
        fBz2.X((fHi)fSj2);
        fSj2.guy();
        fSj2.onChildrenAdded();
        fJe fJe2 = new fJe();
        fJe2.aVI();
        fJe2.setElementMap(fHs2);
        fBz2.X((fHi)fJe2);
        fJe2.guy();
        fJt fJt2 = new fJt();
        fJt2.aVI();
        fJt2.setElementMap(fHs2);
        fJe2.X((fHi)fJt2);
        fJt2.guy();
        fJn fJn2 = new fJn();
        fJn2.aVI();
        fJn2.setElementMap(fHs2);
        fJt2.X((fHi)fJn2);
        fJn2.guy();
        fJx fJx2 = new fJx();
        fJx2.aVI();
        fJx2.setElementMap(fHs2);
        fJn2.X((fHi)fJx2);
        fJx2.guy();
        fJD fJD2 = new fJD();
        fJD2.aVI();
        fJD2.setElementMap(fHs2);
        fJx2.X((fHi)fJD2);
        fJD2.guy();
        fJD2.onChildrenAdded();
        fJx2.onChildrenAdded();
        fJx fJx3 = new fJx();
        fJx3.aVI();
        fJx3.setElementMap(fHs2);
        fJx3.setField("isUnknown");
        fJn2.X((fHi)fJx3);
        fJx3.guy();
        fJw fJw2 = new fJw();
        fJw2.aVI();
        fJw2.setElementMap(fHs2);
        fJx3.X((fHi)fJw2);
        fJw2.guy();
        fJw2.onChildrenAdded();
        fJx3.onChildrenAdded();
        fJn2.onChildrenAdded();
        fJt2.onChildrenAdded();
        String string = "skill";
        fRV fRV2 = new fRV();
        fRV2.aVI();
        fRV2.setElementMap(fHs2);
        if (fHs2 != null && string != null) {
            fHs2.a(string, (fHv)fRV2);
        }
        fJe2.X((fHi)fRV2);
        fRV2.guy();
        fSd fSd2 = new fSd();
        fSd2.aVI();
        fSd2.setElementMap(fHs2);
        fSd2.setAttribute("value");
        fRV2.X((fHi)fSd2);
        fSd2.guy();
        fSd2.onChildrenAdded();
        fRV2.onChildrenAdded();
        fAW fAW3 = fAW.checkOut();
        fAW3.setElementMap(fHs2);
        fJe2.X((fHi)fAW3);
        fAW3.guy();
        fRz fRz2 = fRz.checkOut();
        fRz2.setAlign(fAa.tLN);
        fAW3.X((fHi)fRz2);
        fRz2.guy();
        fRz2.onChildrenAdded();
        fBt fBt2 = new fBt();
        fBt2.aVI();
        fBt2.setElementMap(fHs2);
        fBt2.setDisplaySize(new fSM(26, 26));
        fBt2.setExpandable(false);
        fBt2.setNonBlocking(true);
        fBt2.setPrefSize(new fSM(30, 0));
        fBt2.setScaled(false);
        fAW3.X((fHi)fBt2);
        fBt2.guy();
        fSd fSd3 = new fSd();
        fSd3.aVI();
        fSd3.setElementMap(fHs2);
        fSd3.setAttribute("style");
        fSd3.setField("craftIcon");
        fBt2.X((fHi)fSd3);
        fSd3.guy();
        fSd3.onChildrenAdded();
        fBt fBt3 = fBt2;
        fyY fyY2 = (fyY)fBt3.getAppearance();
        fyY2.setElementMap(fHs2);
        fBt2.X((fHi)fyY2);
        fyY2.guy();
        fKK fKK2 = new fKK();
        fKK2.aVI();
        fKK2.setElementMap(fHs2);
        fKK2.setColor((axb)new awX(new float[]{1.0f, 1.0f, 1.0f, 1.0f}));
        fyY2.X((fHi)fKK2);
        fKK2.guy();
        fKK2.onChildrenAdded();
        fKM fKM2 = new fKM();
        fKM2.aVI();
        fKM2.setElementMap(fHs2);
        fKM2.setColor((axb)new awX(new float[]{0.2f, 0.2f, 0.2f, 1.0f}));
        fKM2.setInsets(new Insets(1, 1, 1, 1));
        fyY2.X((fHi)fKM2);
        fKM2.guy();
        fKM2.onChildrenAdded();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fHs2);
        fzv2.setInsets(new Insets(0, 0, 0, 9));
        fyY2.X((fHi)fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fyY2.onChildrenAdded();
        fBt2.onChildrenAdded();
        fBv fBv2 = new fBv();
        fBv2.aVI();
        fBv2.setElementMap(fHs2);
        fBv2.setExpandable(false);
        fBv2.setPrefSize(new fSM(180, 0));
        fBv2.setStyle("whiteBold");
        fAW3.X((fHi)fBv2);
        fBv2.guy();
        fSd fSd4 = new fSd();
        fSd4.aVI();
        fSd4.setElementMap(fHs2);
        fSd4.setAttribute("text");
        fSd4.setField("name");
        fBv2.X((fHi)fSd4);
        fSd4.guy();
        fSd4.onChildrenAdded();
        fBv2.onChildrenAdded();
        fBv fBv3 = new fBv();
        fBv3.aVI();
        fBv3.setElementMap(fHs2);
        fBv3.setExpandable(false);
        fBv3.setPrefSize(new fSM(50, 0));
        fBv3.setStyle("whiteBold");
        fAW3.X((fHi)fBv3);
        fBv3.guy();
        fSd fSd5 = new fSd();
        fSd5.aVI();
        fSd5.setElementMap(fHs2);
        fSd5.setAttribute("text");
        fSd5.setField("levelText");
        fBv3.X((fHi)fSd5);
        fSd5.guy();
        fSd5.onChildrenAdded();
        fBv3.onChildrenAdded();
        String string2 = "skillXpEditor";
        fDu fDu2 = new fDu();
        fDu2.aVI();
        fDu2.setElementMap(fHs2);
        if (fHs2 != null && string2 != null) {
            fHs2.a(string2, (fHv)fDu2);
        }
        fDu2.setExpandable(false);
        fDu2.setPrefSize(new fSM(50, 0));
        fDu2.setRestrict("[0-9]+");
        fDu2.setStyle("dark");
        fDu2.setText("0");
        fAW3.X((fHi)fDu2);
        fDu2.guy();
        fDu2.onChildrenAdded();
        fAD fAD2 = new fAD();
        fAD2.aVI();
        fAD2.setElementMap(fHs2);
        fAD2.setExpandable(false);
        fMz fMz2 = new fMz();
        fMz2.vw("wakfu.adminCharacterEditor:addSkillXp(skill,skillXpEditor)");
        fAD2.setOnClick(fMz2);
        fAD2.setStyle("smallValid");
        fAW3.X((fHi)fAD2);
        fAD2.guy();
        fSd fSd6 = new fSd();
        fSd6.aVI();
        fSd6.setElementMap(fHs2);
        fSd6.setAttribute("enabled");
        fSd6.setField("isConceptual");
        fAD2.X((fHi)fSd6);
        fSd6.guy();
        fJt fJt3 = new fJt();
        fJt3.aVI();
        fJt3.setElementMap(fHs2);
        fSd6.X((fHi)fJt3);
        fJt3.guy();
        fJw fJw3 = new fJw();
        fJw3.aVI();
        fJw3.setElementMap(fHs2);
        fJt3.X((fHi)fJw3);
        fJw3.guy();
        fJw3.onChildrenAdded();
        fJt3.onChildrenAdded();
        fSd6.onChildrenAdded();
        fAD2.onChildrenAdded();
        fAW3.onChildrenAdded();
        fJe2.onChildrenAdded();
        fBz2.onChildrenAdded();
        return fBz2;
    }
}
