import pathlib

def gen():
    L = []
    w = L.append

    w('// === WAKFU DEV ASSISTANT v4.1 - SENTINEL READY ===')
    w('// 2026-03-14 | LLM classifie, humain decide')
    w('')
    w("const SERVER = 'http://127.0.0.1:8091';")
    w("const VERSION = '4.1';")
    w('')
    w('let initialScanDone = false;')
    w('let scanTimer = null;')
    w('let state = {')
    w('  connected: false,')
    w('  autoMode: false,')
    w('  exchanges: 0,')
    w('  processing: false')
    w('};')
    w('')

    # logExt
    w('function logExt(msg) {')
    w("  console.log('[WAKFU] ' + msg);")
    w("  const d = document.getElementById('wakfu-logs');")
    w('  if (d) {')
    w("    const e = document.createElement('div');")
    w("    e.style.cssText = 'font-size:11px;border-bottom:1px solid #333;padding:2px 0';")
    w("    e.textContent = new Date().toLocaleTimeString() + ' - ' + msg;")
    w('    d.insertBefore(e, d.firstChild);')
    w('    if (d.children.length > 50) d.removeChild(d.lastChild);')
    w('  }')
    w('}')
    w('')

    # serverFetch
    w('async function serverFetch(path, opts = {}) {')
    w('  try {')
    w("    const r = await fetch(SERVER + path, { method: 'GET', headers: { 'Content-Type': 'application/json' }, ...opts });")
    w('    return await r.json();')
    w('  } catch (e) {')
    w("    logExt('Fetch err: ' + path + ' ' + e.message);")
    w('    return null;')
    w('  }')
    w('}')
    w('')

    # checkHealth
    w('async function checkHealth() {')
    w("  const r = await serverFetch('/health');")
    w("  state.connected = !!(r && r.status === 'ok');")
    w('  updatePanel();')
    w('}')
    w('')

    # textarea helpers
    w('function getTextarea() {')
    w("  return document.querySelector('textarea, [contenteditable=\"true\"]');")
    w('}')
    w('')
    w('function clickSendButton() {')
    w("  const btns = document.querySelectorAll('button');")
    w('  for (const b of btns) {')
    w("    const svg = b.querySelector('svg');")
    w('    if (svg && b.offsetParent !== null && !b.disabled) {')
    w('      const r = b.getBoundingClientRect();')
    w('      if (r.width > 20 && r.width < 60) { b.click(); return true; }')
    w('    }')
    w('  }')
    w('  return false;')
    w('}')
    w('')

    # isGenerating
    w('function isGenerating() {')
    w("  const paths = document.querySelectorAll('svg path');")
    w('  for (const p of paths) {')
    w("    const d = p.getAttribute('d');")
    w("    if (d && d.startsWith('M4.75 3A1.75')) return true;")
    w('  }')
    w('  const ta = getTextarea();')
    w('  if (ta && ta.disabled) return true;')
    w('  return false;')
    w('}')
    w('')
    w('function waitForGenerationDone() {')
    w('  return new Promise((resolve) => {')
    w('    let stable = 0;')
    w('    const ck = () => {')
    w('      if (isGenerating()) { stable = 0; setTimeout(ck, 800); }')
    w('      else { stable++; if (stable >= 3) resolve(); else setTimeout(ck, 800); }')
    w('    };')
    w('    setTimeout(ck, 1500);')
    w('  });')
    w('}')
    w('')

    # classifyCode
    w('async function classifyCode(code) {')
    w('  try {')
    w("    const r = await serverFetch('/classify', { method: 'POST', body: JSON.stringify({ code: code }) });")
    w("    if (r && r.classification) return r.classification;")
    w("    return { verdict: 'UNKNOWN', reason: 'no response' };")
    w('  } catch (e) {')
    w("    return { verdict: 'UNKNOWN', reason: e.message };")
    w('  }')
    w('}')
    w('')

    # autoInjectResult
    w('function autoInjectResult(text) {')
    w('  const ta = getTextarea();')
    w("  if (!ta) { logExt('Textarea introuvable'); return; }")
    w("  const msg = 'Resultat de l\\u0027execution (' + text.duration + '):\\n```\\n' + text.output.slice(0, 3000) + '\\n```\\nContinue avec la prochaine etape.';")
    w('  ta.value = msg;')
    w("  ta.dispatchEvent(new Event('input', { bubbles: true }));")
    w('  setTimeout(() => { clickSendButton(); state.exchanges++; updatePanel(); }, 800);')
    w('}')
    w('')

    # detectCodeBlocks
    w('function detectCodeBlocks() {')
    w('  const blocks = [];')
    w("  document.querySelectorAll('pre code, pre').forEach((el, i) => {")
    w("    const code = el.textContent || '';")
    w('    if (code.trim().length < 5) return;')
    w("    let type = 'unknown';")
    w("    const cl = ((el.className || '') + ' ' + ((el.parentElement && el.parentElement.className) || '')).toLowerCase();")
    w("    if (cl.includes('powershell') || cl.includes('ps1')) type = 'powershell';")
    w("    else if (cl.includes('python') || cl.includes('py')) type = 'python';")
    w("    else if (cl.includes('javascript') || cl.includes('js')) type = 'javascript';")
    w("    else if (cl.includes('html')) type = 'html';")
    w("    else if (cl.includes('css')) type = 'css';")
    w("    else if (cl.includes('json')) type = 'json';")
    w("    else if (cl.includes('bash') || cl.includes('shell')) type = 'powershell';")
    w("    else if (code.trimStart().startsWith('$') || code.includes('Write-Host') || code.includes('Invoke-') || code.includes('Get-Content')) type = 'powershell';")
    w("    const codeEl = el.tagName === 'CODE' ? el : (el.querySelector('code') || el);")
    w('    blocks.push({ element: codeEl, code: code, type: type, index: i });')
    w('  });')
    w('  return blocks;')
    w('}')
    w('')

    # addExecButtons
    w('function addExecButtons(block) {')
    w('  const { element, code, type, index } = block;')
    w("  if (element.dataset.wakfuProcessed === 'true') return;")
    w("  element.dataset.wakfuProcessed = 'true';")
    w('')
    w("  const wrapper = document.createElement('div');")
    w("  wrapper.className = 'wakfu-btn-wrapper';")
    w("  wrapper.style.cssText = 'display:flex;gap:6px;margin:6px 0 2px 0;align-items:center';")
    w('')
    w("  let execBtn = null;")
    w("  if (type === 'powershell') {")
    w("    execBtn = document.createElement('button');")
    w("    execBtn.className = 'wakfu-exec-btn';")
    w("    execBtn.textContent = '\\u25B6 Executer';")
    w('    execBtn.onclick = async () => {')
    w("      execBtn.textContent = '\\u23F3 En cours...';")
    w('      execBtn.disabled = true;')
    w('      try {')
    w("        const res = await serverFetch('/execute', { method: 'POST', body: JSON.stringify({ command: code, timeout: 120 }) });")
    w('        execBtn.disabled = false;')
    w('        if (res && res.success) {')
    w("          execBtn.textContent = '\\u2705 OK';")
    w("          execBtn.style.background = '#16a34a';")
    w("          autoInjectResult({ output: res.output || res.result || 'OK', duration: (res.duration || '?') + 's' });")
    w('        } else {')
    w("          execBtn.textContent = '\\u274C Erreur';")
    w("          execBtn.style.background = '#dc2626';")
    w("          autoInjectResult({ output: 'Erreur: ' + (res ? (res.error || JSON.stringify(res)) : 'No response'), duration: '0s' });")
    w('        }')
    w('      } catch (e) {')
    w('        execBtn.disabled = false;')
    w("        execBtn.textContent = '\\u274C Erreur';")
    w("        execBtn.style.background = '#dc2626';")
    w("        autoInjectResult({ output: 'Erreur: ' + e.message, duration: '0s' });")
    w('      }')
    w("      setTimeout(() => { if(execBtn) { execBtn.textContent = '\\u25B6 Executer'; execBtn.style.background = ''; }}, 5000);")
    w('    };')
    w('    wrapper.appendChild(execBtn);')
    w('')
    w('    // SENTINEL classification (affichage seulement, pas auto-click)')
    w('    if (initialScanDone) {')
    w('      const capturedBtn = execBtn;')
    w('      const capturedEl = element;')
    w('      setTimeout(async () => {')
    w("        logExt('SENTINEL: classification bloc #' + index);")
    w('        const result = await classifyCode(code);')
    w("        logExt('SENTINEL: ' + result.verdict + ' - ' + result.reason);")
    w("        const lbl = wrapper.querySelector('.wakfu-type-label');")
    w("        if (result.verdict === 'EXEC_DANGER') {")
    w("          capturedBtn.style.background = '#dc3545';")
    w("          capturedBtn.textContent = '\\u26D4 BLOQUE';")
    w('          capturedBtn.disabled = true;')
    w("          if (lbl) { lbl.textContent = 'DANGER'; lbl.style.background = '#dc3545'; lbl.style.color = '#fff'; }")
    w("        } else if (result.verdict === 'NO_EXEC') {")
    w("          capturedBtn.style.background = '#6c757d';")
    w("          capturedBtn.textContent = 'Exemple';")
    w('          capturedBtn.disabled = true;')
    w("          if (lbl) { lbl.textContent = 'EXEMPLE'; lbl.style.background = '#6c757d'; lbl.style.color = '#fff'; }")
    w("        } else if (result.verdict === 'EXEC_SAFE' && state.autoMode) {")
    w("          if (lbl) { lbl.textContent = 'AUTO'; lbl.style.background = '#28a745'; lbl.style.color = '#fff'; }")
    w("          logExt('AUTO-EXEC: LLM a valide, lancement...');")
    w('          setTimeout(() => { if (capturedBtn && !capturedBtn.disabled) capturedBtn.click(); }, 1500);')
    w("        } else if (result.verdict === 'EXEC_SAFE') {")
    w("          if (lbl) { lbl.textContent = 'SAFE'; lbl.style.background = '#28a745'; lbl.style.color = '#fff'; }")
    w('        }')
    w('      }, 2000);')
    w('    }')
    w('  }')
    w('')
    w("  const copyBtn = document.createElement('button');")
    w("  copyBtn.className = 'wakfu-copy-btn';")
    w("  copyBtn.textContent = '\\u{1F4CB} Copier';")
    w('  copyBtn.onclick = () => {')
    w('    navigator.clipboard.writeText(code);')
    w("    copyBtn.textContent = '\\u2705 Copie!';")
    w("    setTimeout(() => { copyBtn.textContent = '\\u{1F4CB} Copier'; }, 2000);")
    w('  };')
    w('  wrapper.appendChild(copyBtn);')
    w('')
    w("  const typeLabel = document.createElement('span');")
    w("  typeLabel.className = 'wakfu-type-label';")
    w('  typeLabel.textContent = type.toUpperCase();')
    w("  typeLabel.style.cssText = 'font-size:10px;padding:2px 6px;border-radius:3px;background:#374151;color:#9ca3af;align-self:center';")
    w('  wrapper.appendChild(typeLabel);')
    w('')
    w('  element.parentElement.insertBefore(wrapper, element.nextSibling);')
    w('}')
    w('')

    # scanBlocks debounced
    w('function scanBlocks() {')
    w('  const blocks = detectCodeBlocks();')
    w('  let n = 0;')
    w('  blocks.forEach(b => {')
    w("    if (b.element.dataset.wakfuProcessed !== 'true') { addExecButtons(b); n++; }")
    w('  });')
    w("  if (n > 0) logExt('Scan: ' + n + ' nouveaux blocs');")
    w('}')
    w('')
    w('function debouncedScan() {')
    w('  if (scanTimer) clearTimeout(scanTimer);')
    w('  scanTimer = setTimeout(scanBlocks, 500);')
    w('}')
    w('')

    # updatePanel
    w('function updatePanel() {')
    w("  const s = document.getElementById('wakfu-status');")
    w("  const x = document.getElementById('wakfu-exchanges');")
    w("  const a = document.getElementById('wakfu-auto-toggle');")
    w("  if (s) { s.textContent = state.connected ? 'En ligne' : 'Hors ligne'; s.style.color = state.connected ? '#4ade80' : '#f87171'; }")
    w("  if (x) x.textContent = 'Echanges: ' + state.exchanges;")
    w("  if (a) { a.textContent = state.autoMode ? 'AUTO: ON' : 'AUTO: OFF'; a.style.background = state.autoMode ? '#16a34a' : '#dc2626'; }")
    w('}')
    w('')

    # createPanel
    w('function createPanel() {')
    w("  if (document.getElementById('wakfu-panel')) return;")
    w("  const p = document.createElement('div');")
    w("  p.id = 'wakfu-panel';")
    w("  p.innerHTML = '<div style=\"display:flex;align-items:center;justify-content:space-between;margin-bottom:8px\">'")
    w("    + '<strong style=\"color:#60a5fa\">Wakfu Dev v' + VERSION + '</strong>'")
    w("    + '<span id=\"wakfu-status\" style=\"font-size:11px\">...</span></div>'")
    w("    + '<div style=\"display:flex;gap:6px;margin-bottom:6px;flex-wrap:wrap\">'")
    w("    + '<button id=\"wakfu-auto-toggle\" style=\"padding:3px 8px;border:none;border-radius:4px;color:#fff;cursor:pointer;font-size:11px;background:#dc2626\">AUTO: OFF</button>'")
    w("    + '<span id=\"wakfu-exchanges\" style=\"font-size:11px;color:#9ca3af;align-self:center\">Echanges: 0</span></div>'")
    w("    + '<div id=\"wakfu-logs\" style=\"max-height:150px;overflow-y:auto;font-family:monospace;font-size:10px;color:#d1d5db\"></div>';")
    w("  document.body.appendChild(p);")
    w('')
    w("  document.getElementById('wakfu-auto-toggle').addEventListener('click', () => {")
    w('    state.autoMode = !state.autoMode;')
    w('    updatePanel();')
    w("    logExt('Mode auto: ' + (state.autoMode ? 'ON' : 'OFF'));")
    w('  });')
    w('}')
    w('')

    # addStyles
    w('function addStyles() {')
    w("  const s = document.createElement('style');")
    w("  s.textContent = '#wakfu-panel{position:fixed;bottom:10px;right:10px;width:300px;background:#1e1e2e;border:1px solid #374151;border-radius:8px;padding:12px;z-index:99999;font-family:system-ui,sans-serif;box-shadow:0 4px 12px rgba(0,0,0,.5);color:#e5e7eb}'")
    w("    + '.wakfu-exec-btn{background:#2563eb;color:#fff;border:none;padding:4px 10px;border-radius:4px;cursor:pointer;font-size:12px}'")
    w("    + '.wakfu-exec-btn:hover{background:#1d4ed8}'")
    w("    + '.wakfu-copy-btn{background:#374151;color:#d1d5db;border:none;padding:4px 10px;border-radius:4px;cursor:pointer;font-size:12px}'")
    w("    + '.wakfu-copy-btn:hover{background:#4b5563}'")
    w("    + '.wakfu-btn-wrapper{display:flex;gap:6px;margin:6px 0 2px 0}';")
    w("  document.head.appendChild(s);")
    w('}')
    w('')

    # event listener
    w("document.addEventListener('wakfu-action', async (e) => {")
    w("  const action = e.detail ? e.detail.action : '';")
    w("  if (action === 'scan') scanBlocks();")
    w("  else if (action === 'diagnostic') {")
    w("    const r = await serverFetch('/status');")
    w("    logExt('Statut: ' + JSON.stringify(r).slice(0, 200));")
    w('  }')
    w("  else if (action === 'end') {")
    w("    await serverFetch('/session-end', { method: 'POST', body: '{}' });")
    w("    logExt('Session terminee');")
    w('  }')
    w('});')
    w('')

    # observer
    w('const observer = new MutationObserver(() => debouncedScan());')
    w('')

    # init
    w('function init() {')
    w("  logExt('Wakfu Dev Assistant v' + VERSION + ' initialise');")
    w('  addStyles();')
    w('  createPanel();')
    w('  observer.observe(document.body, { childList: true, subtree: true });')
    w("  logExt('Observer DOM actif (debounce 500ms)');")
    w('  checkHealth();')
    w('  setInterval(checkHealth, 15000);')
    w('  scanBlocks();')
    w('  setTimeout(() => {')
    w('    initialScanDone = true;')
    w("    logExt('Scan initial termine - SENTINEL actif pour nouveaux blocs');")
    w('  }, 6000);')
    w('}')
    w('')
    w("if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);")
    w('else init();')

    # Write
    out = pathlib.Path(r'H:\Code\Ankama Dev\wakfu-dev-extension\content.js')
    content = '\n'.join(L)
    out.write_text(content, encoding='utf-8')
    print(f'content.js v4.1 - {len(L)} lignes - {out.stat().st_size} octets')

gen()
