import pathlib, json

def gen():
    lines = []
    a = lines.append
    a('"""')
    a('conductor.py v1.0 - Agent Conductor pour le pipeline auto-codant')
    a('Analyse les resultats et decide la prochaine action.')
    a('Utilise mistral:7b via Ollama.')
    a('"""')
    a('import json, urllib.request, time')
    a('from pathlib import Path')
    a('from datetime import datetime')
    a('')
    a("OLLAMA_URL = 'http://localhost:11434'")
    a("MODEL = 'mistral:7b'")
    a("PROJECT = Path(__file__).resolve().parent.parent")
    a("LOGS = PROJECT / 'logs'")
    a('LOGS.mkdir(exist_ok=True)')
    a("LOG_FILE = LOGS / 'conductor.log'")
    a('')
    a('def log(msg):')
    a("    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')")
    a("    entry = '[' + ts + '] [CONDUCTOR] ' + msg")
    a('    print(entry)')
    a('    try:')
    a("        with open(LOG_FILE, 'a', encoding='utf-8') as f:")
    a("            f.write(entry + chr(10))")
    a('    except:')
    a('        pass')
    a('')
    a('def load_context():')
    a('    ctx = {}')
    a("    briefing = PROJECT / 'BRIEFING.md'")
    a('    if briefing.exists():')
    a("        ctx['briefing'] = briefing.read_text('utf-8', errors='replace')[:2000]")
    a("    handoff = PROJECT / 'SESSION_HANDOFF.md'")
    a('    if handoff.exists():')
    a("        ctx['handoff'] = handoff.read_text('utf-8', errors='replace')[:2000]")
    a("    memory_ep = PROJECT / 'memory' / 'episodes.jsonl'")
    a('    if memory_ep.exists():')
    a("        ep_lines = memory_ep.read_text('utf-8', errors='replace').strip().split(chr(10))")
    a('        recent = ep_lines[-5:] if len(ep_lines) > 5 else ep_lines')
    a("        ctx['recent_episodes'] = [json.loads(l) for l in recent if l.strip()]")
    a('    return ctx')
    a('')
    a('CONDUCTOR_PROMPT = (')
    a("    'Tu es le Conductor, un agent chef de projet IA. '")
    a("    'Tu recois le resultat d une commande executee par Claude Opus. '")
    a("    'Analyse le resultat et decide la prochaine action. '")
    a("    'Contexte projet: {context} '")
    a("    'Commande executee: {command} '")
    a("    'Resultat (code retour: {returncode}): {output} '")
    a("    'Reponds en JSON strict: '")
    a('    \'{{\"action\": \"continue\" ou \"fix\" ou \"escalate\" ou \"done\", \'')
    a('    \'\"message\": \"message a envoyer a Claude Opus\", \'')
    a('    \'\"analysis\": \"ton analyse en 1-2 phrases\", \'')
    a('    \'\"priority\": \"high\" ou \"medium\" ou \"low\"}} \'')
    a("    'Regles: continue=OK donne prochaine instruction, fix=erreur explique quoi corriger, '")
    a("    'escalate=probleme critique pour humain, done=tache terminee. Sois concis.'")
    a(')')
    a('')
    a("def ask_conductor(command, output, returncode, task_context=''):")
    a('    ctx = load_context()')
    a("    context_str = ''")
    a("    if 'briefing' in ctx:")
    a("        context_str += ctx['briefing'][:800]")
    a("    if 'recent_episodes' in ctx:")
    a("        for ep in ctx['recent_episodes']:")
    a("            status = 'OK' if ep.get('success') else 'FAIL'")
    a("            context_str += '[' + status + '] ' + ep.get('context', '')[:60] + ' '")
    a('    if task_context:')
    a("        context_str += ' TACHE: ' + task_context")
    a('    prompt = CONDUCTOR_PROMPT.format(')
    a('        context=context_str[:1500],')
    a('        command=command[:500],')
    a('        output=output[:1500],')
    a('        returncode=returncode')
    a('    )')
    a('    body = json.dumps({')
    a("        'model': MODEL, 'prompt': prompt, 'stream': False,")
    a("        'format': 'json', 'options': {'num_predict': 200, 'temperature': 0.1}")
    a("    }).encode('utf-8')")
    a('    try:')
    a('        start = time.time()')
    a('        req = urllib.request.Request(')
    a("            OLLAMA_URL + '/api/generate',")
    a("            data=body, headers={'Content-Type': 'application/json'})")
    a('        with urllib.request.urlopen(req, timeout=30) as resp:')
    a("            result = json.loads(resp.read().decode('utf-8'))")
    a("            response_text = result.get('response', '').strip()")
    a('            duration = round(time.time() - start, 1)')
    a('            try:')
    a('                decision = json.loads(response_text)')
    a('            except json.JSONDecodeError:')
    a("                decision = {'action': 'continue', 'message': 'Continue.', 'analysis': response_text[:200], 'priority': 'medium'}")
    a("            eval_dur = result.get('eval_duration', 0)")
    a("            tok_s = round(result.get('eval_count', 0) / (eval_dur / 1e9), 1) if eval_dur > 0 else 0")
    a("            log('Decision: ' + decision.get('action', '?') + ' | ' + str(tok_s) + ' tok/s | ' + str(duration) + 's')")
    a("            log('Message: ' + decision.get('message', '')[:100])")
    a("            decision['tokens_per_sec'] = tok_s")
    a("            decision['duration'] = duration")
    a("            decision['model'] = MODEL")
    a('            return decision')
    a('    except Exception as e:')
    a("        log('Erreur Ollama: ' + str(e))")
    a('        if returncode == 0:')
    a("            return {'action': 'continue', 'message': 'Resultat OK. Continue.', 'analysis': 'Execution reussie (fallback)', 'priority': 'low'}")
    a('        else:')
    a("            return {'action': 'fix', 'message': 'Erreur: ' + output[:200], 'analysis': 'Echec (fallback)', 'priority': 'high'}")
    a('')
    a('def format_message(decision):')
    a("    action = decision.get('action', 'continue')")
    a("    msg = decision.get('message', '')")
    a("    analysis = decision.get('analysis', '')")
    a("    if action == 'done': return 'Tache terminee. ' + analysis")
    a("    elif action == 'escalate': return '[ESCALADE] ' + msg")
    a("    elif action == 'fix': return 'Erreur a corriger: ' + msg")
    a('    else: return msg')
    a('')
    a("if __name__ == '__main__':")
    a("    print('=== TEST CONDUCTOR ===')")
    a("    r = ask_conductor('Write-Host test', 'test', 0, 'Test pipeline')")
    a("    print('Decision:', json.dumps(r, indent=2, ensure_ascii=False))")
    a("    print('Message:', format_message(r))")

    out = pathlib.Path(__file__).resolve().parent / 'conductor.py'
    out.write_text(chr(10).join(lines), 'utf-8')
    print('conductor.py -', len(lines), 'lignes -', out.stat().st_size, 'octets')

gen()
