import pathlib

def gen():
    L = []
    w = L.append

    w('"""')
    w('memory_manager.py v1.0 - Systeme de memoire unifiee pour Wakfu Dev Orchestra')
    w('Gere 5 types de memoire en parallele pendant le developpement.')
    w('Sources:')
    w('  - IBM: https://www.ibm.com/think/topics/ai-agent-memory')
    w('  - ML Mastery: https://machinelearningmastery.com/beyond-short-term-memory-the-3-types-of-long-term-memory-ai-agents-need/')
    w('  - Anthropic: https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents')
    w('"""')
    w('')
    w('import json, time, os, re, subprocess')
    w('from pathlib import Path')
    w('from datetime import datetime')
    w('from threading import Thread, Lock')
    w('')
    w('PROJECT = Path(r"H:\\Code\\Ankama Dev\\wakfu-optimizer")')
    w('MEMORY_DIR = PROJECT / "memory"')
    w('MEMORY_DIR.mkdir(exist_ok=True)')
    w('LOGS_DIR = PROJECT / "logs"')
    w('')

    # === FICHIERS MEMOIRE ===
    w('# Fichiers memoire')
    w('EPISODIC_FILE = MEMORY_DIR / "episodes.jsonl"')
    w('PROCEDURAL_FILE = MEMORY_DIR / "procedures.json"')
    w('WORKING_FILE = MEMORY_DIR / "working_notes.md"')
    w('SEMANTIC_FILE = PROJECT / "PROJECT_MEMORY.md"')
    w('BRIEFING_FILE = PROJECT / "BRIEFING.md"')
    w('SESSION_LOG = MEMORY_DIR / "current_session.jsonl"')
    w('')

    # === LOGGER ===
    w('_lock = Lock()')
    w('def log(level, msg):')
    w('    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")')
    w('    entry = f"[{ts}] [MEMORY/{level}] {msg}"')
    w('    print(entry)')
    w('    try:')
    w('        with open(LOGS_DIR / "memory_manager.log", "a", encoding="utf-8") as f:')
    w('            f.write(entry + "\\n")')
    w('    except: pass')
    w('')

    # =============================================
    # EPISODIC MEMORY - Souvenirs d experiences
    # =============================================
    w('class EpisodicMemory:')
    w('    """Stocke les episodes: contexte -> action -> resultat."""')
    w('    def __init__(self):')
    w('        self.episodes = []')
    w('        self._load()')
    w('')
    w('    def _load(self):')
    w('        if EPISODIC_FILE.exists():')
    w('            try:')
    w('                for line in EPISODIC_FILE.read_text("utf-8").strip().split("\\n"):')
    w('                    if line.strip():')
    w('                        self.episodes.append(json.loads(line))')
    w('                log("EPISODIC", f"Charge {len(self.episodes)} episodes")')
    w('            except: pass')
    w('')
    w('    def record(self, context, action, result, success, tags=None):')
    w('        """Enregistre un episode."""')
    w('        episode = {')
    w('            "timestamp": datetime.now().isoformat(),')
    w('            "context": context,')
    w('            "action": action,')
    w('            "result": result[:500] if isinstance(result, str) else str(result)[:500],')
    w('            "success": success,')
    w('            "tags": tags or []')
    w('        }')
    w('        self.episodes.append(episode)')
    w('        with _lock:')
    w('            with open(EPISODIC_FILE, "a", encoding="utf-8") as f:')
    w('                f.write(json.dumps(episode, ensure_ascii=False) + "\\n")')
    w('        log("EPISODIC", f"Episode enregistre: {context[:60]} -> {\"OK\" if success else \"FAIL\"}")')
    w('')
    w('    def search(self, query, limit=5):')
    w('        """Recherche les episodes similaires (par mots-cles)."""')
    w('        words = set(query.lower().split())')
    w('        scored = []')
    w('        for ep in self.episodes:')
    w('            text = f"{ep[\"context\"]} {ep[\"action\"]} {\" \".join(ep.get(\"tags\", []))}".lower()')
    w('            score = len(words & set(text.split()))')
    w('            if score > 0:')
    w('                scored.append((score, ep))')
    w('        scored.sort(key=lambda x: -x[0])')
    w('        return [ep for _, ep in scored[:limit]]')
    w('')
    w('    def get_recent(self, n=10):')
    w('        return self.episodes[-n:]')
    w('')
    w('    def get_failures(self, n=10):')
    w('        fails = [e for e in self.episodes if not e["success"]]')
    w('        return fails[-n:]')
    w('')
    w('    def summarize_for_briefing(self, n=5):')
    w('        """Resume les derniers episodes pour injection dans le BRIEFING."""')
    w('        recent = self.get_recent(n)')
    w('        if not recent: return "Aucun episode enregistre."')
    w('        lines = []')
    w('        for ep in recent:')
    w('            status = "OK" if ep["success"] else "FAIL"')
    w('            ts = ep["timestamp"][11:19]')
    w('            lines.append(f"- [{status}] {ts} {ep[\"context\"][:80]}")')
    w('        return "\\n".join(lines)')
    w('')

    # =============================================
    # PROCEDURAL MEMORY - Savoir-faire
    # =============================================
    w('class ProceduralMemory:')
    w('    """Stocke les procedures: recettes reutilisables."""')
    w('    def __init__(self):')
    w('        self.procedures = {}')
    w('        self._load()')
    w('')
    w('    def _load(self):')
    w('        if PROCEDURAL_FILE.exists():')
    w('            try:')
    w('                self.procedures = json.loads(PROCEDURAL_FILE.read_text("utf-8"))')
    w('                log("PROCEDURAL", f"Charge {len(self.procedures)} procedures")')
    w('            except: pass')
    w('')
    w('    def _save(self):')
    w('        with _lock:')
    w('            PROCEDURAL_FILE.write_text(json.dumps(self.procedures, indent=2, ensure_ascii=False), "utf-8")')
    w('')
    w('    def record(self, name, steps, tags=None, source_episode=None):')
    w('        """Enregistre ou met a jour une procedure."""')
    w('        self.procedures[name] = {')
    w('            "steps": steps,')
    w('            "tags": tags or [],')
    w('            "last_used": datetime.now().isoformat(),')
    w('            "use_count": self.procedures.get(name, {}).get("use_count", 0) + 1,')
    w('            "source_episode": source_episode')
    w('        }')
    w('        self._save()')
    w('        log("PROCEDURAL", f"Procedure enregistree: {name}")')
    w('')
    w('    def get(self, name):')
    w('        return self.procedures.get(name)')
    w('')
    w('    def search(self, query):')
    w('        """Recherche par mots-cles dans noms et tags."""')
    w('        words = set(query.lower().split())')
    w('        results = []')
    w('        for name, proc in self.procedures.items():')
    w('            text = f"{name} {\" \".join(proc.get(\"tags\", []))}".lower()')
    w('            score = len(words & set(text.split()))')
    w('            if score > 0:')
    w('                results.append((score, name, proc))')
    w('        results.sort(key=lambda x: -x[0])')
    w('        return [(n, p) for _, n, p in results]')
    w('')
    w('    def summarize_for_briefing(self):')
    w('        """Resume les procedures les plus utilisees."""')
    w('        if not self.procedures: return "Aucune procedure enregistree."')
    w('        sorted_procs = sorted(self.procedures.items(), key=lambda x: -x[1].get("use_count", 0))')
    w('        lines = []')
    w('        for name, proc in sorted_procs[:8]:')
    w('            count = proc.get("use_count", 0)')
    w('            lines.append(f"- {name} (x{count}): {len(proc[\"steps\"])} etapes")')
    w('        return "\\n".join(lines)')
    w('')

    # =============================================
    # WORKING MEMORY - Notes de session
    # =============================================
    w('class WorkingMemory:')
    w('    """Notes de travail pour la session en cours."""')
    w('    def __init__(self):')
    w('        self.notes = []')
    w('        self.task_stack = []')
    w('')
    w('    def add_note(self, note):')
    w('        entry = {"time": datetime.now().isoformat(), "note": note}')
    w('        self.notes.append(entry)')
    w('        self._save()')
    w('')
    w('    def push_task(self, task):')
    w('        self.task_stack.append({"task": task, "started": datetime.now().isoformat()})')
    w('        log("WORKING", f"Tache empilee: {task}")')
    w('')
    w('    def pop_task(self):')
    w('        if self.task_stack:')
    w('            done = self.task_stack.pop()')
    w('            log("WORKING", f"Tache terminee: {done[\"task\"]}")')
    w('            return done')
    w('        return None')
    w('')
    w('    def current_task(self):')
    w('        return self.task_stack[-1]["task"] if self.task_stack else None')
    w('')
    w('    def _save(self):')
    w('        lines = [f"# Working Notes - {datetime.now().strftime(\"%Y-%m-%d %H:%M\")}", ""]')
    w('        if self.task_stack:')
    w('            lines.append("## Taches en cours")')
    w('            for t in self.task_stack:')
    w('                lines.append(f"- [ ] {t[\"task\"]} (depuis {t[\"started\"][11:19]})")')
    w('            lines.append("")')
    w('        if self.notes:')
    w('            lines.append("## Notes")')
    w('            for n in self.notes[-20:]:')
    w('                lines.append(f"- {n[\"time\"][11:19]} {n[\"note\"]}")')
    w('        with _lock:')
    w('            WORKING_FILE.write_text("\\n".join(lines), "utf-8")')
    w('')
    w('    def summarize(self):')
    w('        task = self.current_task() or "Aucune"')
    w('        return f"Tache: {task} | Notes: {len(self.notes)}"')
    w('')

    # =============================================
    # SESSION TRACKER - Log de session
    # =============================================
    w('class SessionTracker:')
    w('    """Suit les evenements de la session pour nourrir les autres memoires."""')
    w('    def __init__(self):')
    w('        self.events = []')
    w('        self.session_start = datetime.now().isoformat()')
    w('        self.files_modified = set()')
    w('        self.commands_run = 0')
    w('        self.errors = 0')
    w('')
    w('    def track_command(self, command, result, success, duration=0):')
    w('        """Enregistre une commande executee."""')
    w('        event = {')
    w('            "type": "command",')
    w('            "time": datetime.now().isoformat(),')
    w('            "command": command[:200],')
    w('            "success": success,')
    w('            "duration": duration')
    w('        }')
    w('        self.events.append(event)')
    w('        self.commands_run += 1')
    w('        if not success: self.errors += 1')
    w('        with _lock:')
    w('            with open(SESSION_LOG, "a", encoding="utf-8") as f:')
    w('                f.write(json.dumps(event, ensure_ascii=False) + "\\n")')
    w('')
    w('    def track_file_change(self, filepath):')
    w('        self.files_modified.add(filepath)')
    w('')
    w('    def track_ext_log(self, log_entry):')
    w('        """Enregistre un log de l extension Chrome."""')
    w('        event = {')
    w('            "type": "ext_log",')
    w('            "time": datetime.now().isoformat(),')
    w('            "message": log_entry[:300]')
    w('        }')
    w('        self.events.append(event)')
    w('')
    w('    def get_summary(self):')
    w('        return {')
    w('            "session_start": self.session_start,')
    w('            "duration_min": round((datetime.now() - datetime.fromisoformat(self.session_start)).total_seconds() / 60, 1),')
    w('            "commands_run": self.commands_run,')
    w('            "errors": self.errors,')
    w('            "files_modified": list(self.files_modified),')
    w('            "events_count": len(self.events)')
    w('        }')
    w('')

    # =============================================
    # DOCBOT - Agent documentaliste (llama3.2:3b)
    # =============================================
    w('class DocBot:')
    w('    """Agent local qui met a jour la documentation via llama3.2:3b."""')
    w('    MODEL = "llama3.2:3b"')
    w('    OLLAMA_URL = "http://localhost:11434"')
    w('')
    w('    def _ask(self, prompt, max_tokens=300):')
    w('        import urllib.request')
    w('        body = json.dumps({')
    w('            "model": self.MODEL, "prompt": prompt, "stream": False,')
    w('            "options": {"num_predict": max_tokens, "temperature": 0.3}')
    w('        }).encode("utf-8")')
    w('        try:')
    w('            req = urllib.request.Request(')
    w('                f"{self.OLLAMA_URL}/api/generate", data=body,')
    w('                headers={"Content-Type": "application/json"})')
    w('            with urllib.request.urlopen(req, timeout=30) as resp:')
    w('                return json.loads(resp.read().decode("utf-8")).get("response", "").strip()')
    w('        except Exception as e:')
    w('            log("DOCBOT", f"Erreur Ollama: {e}")')
    w('            return None')
    w('')
    w('    def generate_episode_tags(self, context, action, result):')
    w('        """Genere des tags pour un episode."""')
    w('        prompt = f"Generate 3-5 short tags for this development event. Reply with ONLY comma-separated tags.\\nContext: {context[:200]}\\nAction: {action[:200]}\\nResult: {result[:100]}"')
    w('        resp = self._ask(prompt, 50)')
    w('        if resp:')
    w('            return [t.strip().lower() for t in resp.split(",") if t.strip()]')
    w('        return []')
    w('')
    w('    def extract_procedure(self, episodes):')
    w('        """Detecte une procedure recurrente dans les episodes."""')
    w('        if len(episodes) < 2: return None')
    w('        recent = episodes[-5:]')
    w('        context_text = "\\n".join([f"- {e[\"context\"][:80]}: {e[\"action\"][:80]}" for e in recent])')
    w('        prompt = f"These are recent development actions. If there is a repeated pattern, describe it as a reusable procedure with numbered steps. If no pattern, reply NONE.\\n{context_text}"')
    w('        resp = self._ask(prompt, 200)')
    w('        if resp and "NONE" not in resp.upper():')
    w('            return resp')
    w('        return None')
    w('')
    w('    def generate_changelog_entry(self, files_modified, commands_summary):')
    w('        """Genere une entree de changelog."""')
    w('        prompt = f"Write a brief changelog entry (1-2 lines) for these changes:\\nFiles: {files_modified[:300]}\\nActions: {commands_summary[:300]}"')
    w('        return self._ask(prompt, 100)')
    w('')

    # =============================================
    # REVIEWER - Agent relecteur (deepseek-coder-v2)
    # =============================================
    w('class Reviewer:')
    w('    """Agent local qui review le code ecrit via deepseek-coder-v2."""')
    w('    MODEL = "deepseek-coder-v2:latest"')
    w('    OLLAMA_URL = "http://localhost:11434"')
    w('')
    w('    def _ask(self, prompt, max_tokens=500):')
    w('        import urllib.request')
    w('        body = json.dumps({')
    w('            "model": self.MODEL, "prompt": prompt, "stream": False,')
    w('            "options": {"num_predict": max_tokens, "temperature": 0.1}')
    w('        }).encode("utf-8")')
    w('        try:')
    w('            req = urllib.request.Request(')
    w('                f"{self.OLLAMA_URL}/api/generate", data=body,')
    w('                headers={"Content-Type": "application/json"})')
    w('            with urllib.request.urlopen(req, timeout=60) as resp:')
    w('                return json.loads(resp.read().decode("utf-8")).get("response", "").strip()')
    w('        except Exception as e:')
    w('            log("REVIEWER", f"Erreur Ollama: {e}")')
    w('            return None')
    w('')
    w('    def review_file(self, filepath, content):')
    w('        """Review un fichier modifie."""')
    w('        prompt = f"Review this code file for bugs, missing imports, or regressions. Be brief. File: {filepath}\\n```\\n{content[:3000]}\\n```"')
    w('        resp = self._ask(prompt)')
    w('        if resp:')
    w('            log("REVIEWER", f"Review {filepath}: {resp[:100]}")')
    w('        return resp')
    w('')
    w('    def check_regression(self, filepath, old_content, new_content):')
    w('        """Verifie si une modification introduit une regression."""')
    w('        prompt = f"Compare old and new versions of {filepath}. Are there any regressions or lost features? Reply SAFE if OK, or describe the regression.\\nOLD (last 50 lines):\\n{old_content[-2000:]}\\nNEW (last 50 lines):\\n{new_content[-2000:]}"')
    w('        resp = self._ask(prompt)')
    w('        if resp:')
    w('            is_safe = "SAFE" in resp.upper()[:20]')
    w('            log("REVIEWER", f"Regression check {filepath}: {\"SAFE\" if is_safe else \"ISSUE: \" + resp[:80]}")')
    w('            return {"safe": is_safe, "details": resp}')
    w('        return {"safe": True, "details": "Review unavailable"}')
    w('')

    # =============================================
    # MEMORY MANAGER - Orchestrateur central
    # =============================================
    w('class MemoryManager:')
    w('    """Orchestrateur central des 5 memoires."""')
    w('    def __init__(self):')
    w('        self.episodic = EpisodicMemory()')
    w('        self.procedural = ProceduralMemory()')
    w('        self.working = WorkingMemory()')
    w('        self.session = SessionTracker()')
    w('        self.docbot = DocBot()')
    w('        self.reviewer = Reviewer()')
    w('        log("MANAGER", "Memory Manager v1.0 initialise")')
    w('        log("MANAGER", f"Episodes: {len(self.episodic.episodes)} | Procedures: {len(self.procedural.procedures)}")')
    w('')
    w('    def on_command_executed(self, command, result, success, duration=0):')
    w('        """Appele apres chaque execution de commande."""')
    w('        # 1. Session tracking')
    w('        self.session.track_command(command, result, success, duration)')
    w('')
    w('        # 2. Episode recording (async via thread)')
    w('        def _record():')
    w('            context = self._extract_context(command)')
    w('            tags = self.docbot.generate_episode_tags(context, command[:200], result[:200])')
    w('            self.episodic.record(context, command[:300], result[:300], success, tags)')
    w('        Thread(target=_record, daemon=True).start()')
    w('')
    w('    def on_file_modified(self, filepath, old_content=None, new_content=None):')
    w('        """Appele quand un fichier est modifie."""')
    w('        self.session.track_file_change(filepath)')
    w('')
    w('        # Review en background si c est du code')
    w('        if new_content and filepath.endswith((".tsx", ".ts", ".py", ".js")):')
    w('            def _review():')
    w('                if old_content:')
    w('                    result = self.reviewer.check_regression(filepath, old_content, new_content)')
    w('                    if not result["safe"]:')
    w('                        self.working.add_note(f"REGRESSION DETECTEE dans {filepath}: {result[\"details\"][:100]}")')
    w('                        self.episodic.record(f"Regression dans {filepath}", "modification fichier", result["details"][:200], False, ["regression", filepath.split("/")[-1]])')
    w('                else:')
    w('                    self.reviewer.review_file(filepath, new_content)')
    w('            Thread(target=_review, daemon=True).start()')
    w('')
    w('    def on_ext_log(self, message):')
    w('        """Appele quand l extension envoie un log."""')
    w('        self.session.track_ext_log(message)')
    w('')
    w('    def get_briefing_context(self):')
    w('        """Genere le contexte a injecter dans le BRIEFING pour la prochaine session."""')
    w('        parts = []')
    w('        parts.append("## MEMOIRE EPISODIQUE (derniers evenements)")')
    w('        parts.append(self.episodic.summarize_for_briefing(8))')
    w('        parts.append("")')
    w('        parts.append("## MEMOIRE PROCEDURALE (savoir-faire)")')
    w('        parts.append(self.procedural.summarize_for_briefing())')
    w('        parts.append("")')
    w('        parts.append("## SESSION PRECEDENTE")')
    w('        summary = self.session.get_summary()')
    w('        parts.append(f"Duree: {summary[\"duration_min\"]}min | Commandes: {summary[\"commands_run\"]} | Erreurs: {summary[\"errors\"]}")')
    w('        parts.append(f"Fichiers modifies: {\", \".join(summary[\"files_modified\"][:10])}")')
    w('        parts.append("")')
    w('        failures = self.episodic.get_failures(3)')
    w('        if failures:')
    w('            parts.append("## ERREURS RECENTES (ne pas repeter)")')
    w('            for f in failures:')
    w('                parts.append(f"- {f[\"context\"][:80]}: {f[\"result\"][:100]}")')
    w('        return "\\n".join(parts)')
    w('')
    w('    def check_procedures(self):')
    w('        """Detecte de nouvelles procedures depuis les episodes recents."""')
    w('        recent = self.episodic.get_recent(10)')
    w('        result = self.docbot.extract_procedure(recent)')
    w('        if result:')
    w('            name = f"auto_{datetime.now().strftime(\"%Y%m%d_%H%M\")}"')
    w('            self.procedural.record(name, result.split("\\n"), ["auto-detected"])')
    w('            log("MANAGER", f"Nouvelle procedure detectee: {name}")')
    w('')
    w('    def end_session(self):')
    w('        """Finalise la session: met a jour BRIEFING, detecte les procedures."""')
    w('        log("MANAGER", "Fin de session - consolidation memoire...")')
    w('')
    w('        # Detecter procedures')
    w('        self.check_procedures()')
    w('')
    w('        # Generer contexte briefing')
    w('        memory_context = self.get_briefing_context()')
    w('')
    w('        # Mettre a jour BRIEFING.md')
    w('        try:')
    w('            briefing = BRIEFING_FILE.read_text("utf-8") if BRIEFING_FILE.exists() else ""')
    w('            marker = "## MEMOIRE EPISODIQUE"')
    w('            if marker in briefing:')
    w('                briefing = briefing[:briefing.index(marker)]')
    w('            briefing = briefing.rstrip() + "\\n\\n" + memory_context')
    w('            BRIEFING_FILE.write_text(briefing, "utf-8")')
    w('            log("MANAGER", "BRIEFING.md mis a jour avec memoire")')
    w('        except Exception as e:')
    w('            log("MANAGER", f"Erreur MAJ briefing: {e}")')
    w('')
    w('        # Reset session')
    w('        summary = self.session.get_summary()')
    w('        log("MANAGER", f"Session terminee: {summary[\"commands_run\"]} commandes, {summary[\"errors\"]} erreurs, {len(summary[\"files_modified\"])} fichiers modifies")')
    w('        return summary')
    w('')
    w('    def _extract_context(self, command):')
    w('        """Extrait le contexte lisible d une commande."""')
    w('        cmd = command[:200]')
    w('        if "Write-Host" in cmd:')
    w('            return "Affichage/diagnostic PowerShell"')
    w('        elif "Set-Content" in cmd or "write_text" in cmd:')
    w('            return "Ecriture de fichier"')
    w('        elif "Get-Content" in cmd or "read_text" in cmd:')
    w('            return "Lecture de fichier"')
    w('        elif "pip install" in cmd:')
    w('            return "Installation de package Python"')
    w('        elif "npm" in cmd:')
    w('            return "Commande npm"')
    w('        elif "git" in cmd:')
    w('            return "Operation git"')
    w('        elif "Invoke-RestMethod" in cmd:')
    w('            return "Appel API/serveur"')
    w('        elif "python" in cmd:')
    w('            return "Execution script Python"')
    w('        else:')
    w('            return f"Commande: {cmd[:80]}"')
    w('')

    # === SINGLETON ===
    w('# Instance globale')
    w('_manager = None')
    w('')
    w('def get_manager():')
    w('    global _manager')
    w('    if _manager is None:')
    w('        _manager = MemoryManager()')
    w('    return _manager')
    w('')

    # === TEST ===
    w('if __name__ == "__main__":')
    w('    print("=== MEMORY MANAGER v1.0 - Test ===")')
    w('    mm = get_manager()')
    w('    print()')
    w('    print("--- Test Episodic ---")')
    w('    mm.on_command_executed("Write-Host Hello", "Hello", True, 0.3)')
    w('    time.sleep(2)')
    w('    print(f"Episodes: {len(mm.episodic.episodes)}")')
    w('    print()')
    w('    print("--- Test Procedural ---")')
    w('    mm.procedural.record("deploy_frontend", ["npm run build", "git push", "vercel deploy"], ["deploy", "frontend"])')
    w('    print(f"Procedures: {len(mm.procedural.procedures)}")')
    w('    print()')
    w('    print("--- Test Briefing Context ---")')
    w('    ctx = mm.get_briefing_context()')
    w('    print(ctx[:500])')
    w('    print()')
    w('    print("=== FIN TEST ===")')

    # Write file
    content = '\n'.join(L)
    target = pathlib.Path(r'H:\Code\Ankama Dev\wakfu-optimizer\scripts\memory_manager.py')
    target.write_text(content, encoding='utf-8')
    print(f'memory_manager.py v1.0 - {len(L)} lignes - {target.stat().st_size} octets')

gen()
